"use client";

import { useState, useRef, useEffect } from "react";
import ReactMarkdown, { type Components } from "react-markdown";
import { SignInButton, SignUpButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";

interface Message {
  role: "user" | "ai";
  content: string;
  id: string;
}

interface PinnedItem {
  id: string;
  content: string;
}

export default function Home() {
  const [messages, setMessages] = useState<Message[]>([
    {
      role: "ai",
      content:
        "👋 **Welcome.** Tell me what ingredients you have — and we’ll turn it into something exceptional.",
      id: "intro",
    },
  ]);

  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [pinnedItems, setPinnedItems] = useState<PinnedItem[]>([]);
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  
  // NEW: State for the currently viewed recipe modal
  const [activeRecipe, setActiveRecipe] = useState<PinnedItem | null>(null);

  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({
      behavior: "smooth",
    });
  }, [messages]);

  // ---------- ACTIONS ----------
  
  const resetChat = () => {
    if (window.confirm("Start a new cooking session? This will clear the current chat.")) {
      setMessages([
        {
          role: "ai",
          content: "👋 **Ready for a new dish.** What ingredients are we working with now?",
          id: Date.now().toString(),
        },
      ]);
    }
  };

  const printRecipe = (content: string) => {
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>CHEFgpt Recipe</title>
            <style>
              body { font-family: sans-serif; padding: 40px; color: #333; }
              h1, h2, h3 { color: #d97706; }
              ul { line-height: 1.6; }
              .footer { margin-top: 40px; font-size: 12px; color: #888; border-top: 1px solid #eee; padding-top: 10px; }
            </style>
          </head>
          <body>
            ${content.replace(/\*\*(.*?)\*\*/g, '<b>$1</b>').replace(/\n/g, '<br>')}
            <div class="footer">Generated by Chef Noypi AI</div>
            <script>window.print();</script>
          </body>
        </html>
      `);
      printWindow.document.close();
    }
  };

  const sendMessage = async (text: string) => {
    if (!text.trim()) return;

    const userMessage: Message = {
      role: "user",
      content: text,
      id: Date.now().toString(),
    };

    setMessages((prev) => [...prev, userMessage]);
    setInput("");
    setLoading(true);

    try {
      const historyPayload = messages.slice(1).map((msg) => ({
        role: msg.role === "ai" ? "model" : "user",
        content: msg.content,
      }));

      const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";

      const response = await fetch(`${API_URL}/chat`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          history: historyPayload,
          message: text,
        }),
      });

      const data = await response.json();

      setMessages((prev) => [
        ...prev,
        {
          role: "ai",
          content: data.response,
          id: Date.now().toString(),
        },
      ]);
    } catch (err) {
      setMessages((prev) => [
        ...prev,
        {
          role: "ai",
          content: "⚠️ **Connection issue.** Is the backend running?",
          id: "error",
        },
      ]);
    }

    setLoading(false);
  };

  const togglePin = (msg: Message) => {
    const exists = pinnedItems.some((i) => i.id === msg.id);

    if (exists) {
      setPinnedItems((prev) => prev.filter((i) => i.id !== msg.id));
    } else {
      setPinnedItems((prev) => [...prev, { id: msg.id, content: msg.content }]);
      setIsSidebarOpen(true);
    }
  };

  // ---------- MARKDOWN ----------
  const markdownComponents: Components = {
    strong: (props) => <span className="font-semibold text-orange-300" {...props} />,
    p: (props) => <p className="leading-relaxed text-[15.5px] mb-2" {...props} />,
    ul: (props) => <ul className="list-disc ml-4 mb-2 space-y-1" {...props} />,
    li: (props) => <li className="pl-1 opacity-90" {...props} />,
    h2: (props) => <h2 className="text-lg font-bold text-white mt-4 mb-2 border-b border-white/10 pb-1" {...props} />,
    h3: (props) => <h3 className="text-md font-semibold text-orange-400 mt-3 mb-1" {...props} />,
  };

  return (
    <div className="h-screen flex overflow-hidden text-neutral-200 font-[Plus_Jakarta_Sans]">
      
      {/* BACKGROUND */}
      <div className="fixed inset-0 -z-10 bg-[radial-gradient(circle_at_top,rgba(255,115,0,0.15),transparent_40%),linear-gradient(to_bottom,#020617,#020617)]" />

      {/* --- RECIPE MODAL OVERLAY --- */}
      {activeRecipe && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
          <div className="bg-[#111] border border-white/10 rounded-2xl w-full max-w-2xl max-h-[85vh] flex flex-col shadow-2xl overflow-hidden animate-in fade-in zoom-in duration-200">
            {/* Modal Header */}
            <div className="flex items-center justify-between p-4 border-b border-white/10 bg-white/[0.02]">
               <h3 className="font-semibold text-orange-400">Recipe Card</h3>
               <div className="flex gap-2">
                 <button 
                   onClick={() => printRecipe(activeRecipe.content)}
                   className="p-2 hover:bg-white/10 rounded-lg text-neutral-400 hover:text-white transition"
                   title="Print"
                 >
                   🖨️
                 </button>
                 <button 
                   onClick={() => setActiveRecipe(null)}
                   className="p-2 hover:bg-white/10 rounded-lg text-neutral-400 hover:text-white transition"
                 >
                   ✕
                 </button>
               </div>
            </div>
            {/* Modal Body */}
            <div className="p-6 overflow-y-auto">
               <ReactMarkdown components={markdownComponents}>
                 {activeRecipe.content}
               </ReactMarkdown>
            </div>
          </div>
        </div>
      )}

      {/* MAIN CONTENT */}
      <div className="flex-1 flex flex-col relative z-10">
        
        {/* HEADER */}
        <header className="h-16 px-6 lg:px-8 flex items-center justify-between border-b border-white/5 backdrop-blur-xl bg-white/[0.02]">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 lg:w-9 lg:h-9 rounded-xl bg-gradient-to-br from-orange-500 to-amber-500 shadow-lg flex items-center justify-center text-black font-bold text-sm">
               👨‍🍳
            </div>
            <div>
              <h1 className="font-semibold tracking-tight text-white leading-tight">CHEFgpt</h1>
              <span className="text-[10px] lg:text-xs text-orange-400 uppercase tracking-wider font-medium">AI Kusina Assistant</span>
            </div>
          </div>

          <div className="flex items-center gap-4">
             {messages.length > 1 && (
                <button 
                  onClick={resetChat}
                  className="hidden sm:flex items-center gap-2 text-sm text-neutral-400 hover:text-white transition"
                  title="Clear Chat History"
                >
                  <span className="text-lg">🗑️</span>
                  <span className="hidden lg:inline">New Chat</span>
                </button>
             )}

            <div className="w-px h-6 bg-white/10 mx-1 hidden sm:block"></div>

            <SignedOut>
                <SignInButton mode="modal">
                    <button className="text-sm font-medium text-neutral-400 hover:text-white transition-colors">Sign In</button>
                </SignInButton>
                <SignUpButton mode="modal">
                    <button className="px-3 py-1.5 text-sm font-medium bg-orange-600 hover:bg-orange-500 text-white rounded-lg transition-colors">Get Started</button>
                </SignUpButton>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>

            <button
              onClick={() => setIsSidebarOpen(!isSidebarOpen)}
              className={`px-3 py-1.5 rounded-lg border transition text-sm ${
                isSidebarOpen 
                ? "bg-orange-500/10 border-orange-500/50 text-orange-400" 
                : "bg-white/[0.04] border-white/5 hover:bg-white/[0.07] text-neutral-400"
              }`}
            >
              {isSidebarOpen ? "Hide" : "Cookbook"}
            </button>
          </div>
        </header>

        {/* MESSAGES */}
        <div className="flex-1 overflow-y-auto px-4 lg:px-6 py-10 space-y-6 scrollbar-thin scrollbar-thumb-white/10 scrollbar-track-transparent">
          {messages.map((msg) => (
            <div key={msg.id} className={`flex ${msg.role === "user" ? "justify-end" : "justify-start"}`}>
              <div className="relative group max-w-[85%] lg:max-w-[760px]">
                
                <div className={`rounded-3xl px-6 py-5 shadow-2xl border text-sm lg:text-base ${
                    msg.role === "user"
                      ? "bg-gradient-to-br from-orange-500 to-amber-500 text-black border-transparent font-medium"
                      : "bg-[#0A0A0A] backdrop-blur-xl border-white/10 shadow-black/50"
                  }`}>
                  <ReactMarkdown components={markdownComponents}>
                    {msg.content}
                  </ReactMarkdown>
                </div>

                {msg.role === "ai" && (
                  <div className="absolute -right-12 top-2 flex flex-col gap-2 opacity-0 group-hover:opacity-100 transition">
                    <button
                      onClick={() => togglePin(msg)}
                      title="Save to Cookbook"
                      className="p-2 rounded-full hover:bg-white/10 text-orange-400 transition"
                    >
                      📌
                    </button>
                    <button
                      onClick={() => printRecipe(msg.content)}
                      title="Print Recipe"
                      className="p-2 rounded-full hover:bg-white/10 text-neutral-400 hover:text-white transition"
                    >
                      🖨️
                    </button>
                  </div>
                )}
              </div>
            </div>
          ))}
          {loading && (
            <div className="flex gap-2 items-center text-sm text-neutral-500 animate-pulse px-6">
              <div className="w-2 h-2 rounded-full bg-orange-500"></div>
              Computing Diskarte...
            </div>
          )}
          <div ref={messagesEndRef} />
        </div>

        {/* COMPOSER */}
        <div className="sticky bottom-6 flex justify-center px-4">
          <div className="w-full max-w-3xl bg-[#0F0F0F]/80 backdrop-blur-2xl border border-white/10 rounded-2xl shadow-2xl flex gap-3 p-2 lg:p-3 items-end ring-1 ring-white/5">
            <textarea
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Ex: I have sardines, flour, and 1 egg..."
              rows={1}
              className="flex-1 bg-transparent outline-none resize-none px-3 py-3 max-h-32 text-neutral-200 placeholder:text-neutral-600"
              onKeyDown={(e) => {
                if (e.key === "Enter" && !e.shiftKey) {
                  e.preventDefault();
                  sendMessage(input);
                }
              }}
            />
            <button
              onClick={() => sendMessage(input)}
              disabled={!input.trim() || loading}
              className="px-5 py-2.5 rounded-xl bg-gradient-to-br from-orange-500 to-amber-600 text-black font-bold disabled:opacity-40 disabled:cursor-not-allowed hover:brightness-110 active:scale-[0.97] transition"
            >
              Send
            </button>
          </div>
        </div>
      </div>

      {/* SIDEBAR */}
      <div className={`fixed inset-y-0 right-0 lg:relative overflow-hidden transition-all duration-500 ease-[cubic-bezier(0.23,1,0.32,1)] ${
    isSidebarOpen ? "w-80 translate-x-0" : "w-0 translate-x-20 opacity-0 lg:opacity-100"
} border-l border-white/5 backdrop-blur-2xl bg-[#050505]/90 z-20 shadow-2xl`}>
        <div className="p-6 font-semibold flex justify-between items-center border-b border-white/5">
          <span className="text-orange-400">Saved Recipes</span>
          <button onClick={() => setIsSidebarOpen(false)} className="lg:hidden text-neutral-500">✕</button>
        </div>
        <div className="px-4 py-4 space-y-3 overflow-y-auto h-[calc(100vh-80px)]">
          {pinnedItems.length === 0 ? (
             <div className="text-sm opacity-40 text-center mt-10 italic px-6">
                Click the 📌 icon on a recipe to save it here.
             </div>
          ) : (
             pinnedItems.map((item) => (
                <div 
                  key={item.id} 
                  onClick={() => setActiveRecipe(item)} // OPEN MODAL
                  className="p-4 rounded-2xl bg-white/[0.03] border border-white/5 hover:border-orange-500/30 hover:bg-white/[0.05] transition cursor-pointer group relative"
                >
                   <div className="line-clamp-3 text-xs text-neutral-300 pointer-events-none mb-1">
                      <ReactMarkdown allowedElements={["h2", "strong"]}>{item.content}</ReactMarkdown>
                   </div>
                   <div className="text-[10px] text-orange-400/80 font-medium">Click to view full recipe</div>
                   
                   {/* DELETE BUTTON */}
                   <button 
                      onClick={(e) => { 
                          e.stopPropagation(); 
                          setPinnedItems(prev => prev.filter(p => p.id !== item.id)) 
                      }}
                      className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 text-neutral-500 hover:text-red-400 transition p-1"
                   >✕</button>
                </div>
             ))
          )}
        </div>
      </div>
    </div>
  );
}